channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.9.13
  
  - pip=22.1.2
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    - rpaframework==22.5.2    # https://rpaframework.org/releasenotes.html
    - pandas==1.2.3
    - requests==2.28.2        # https://pypi.org/project/requests/#history
    - matplotlib==3.3.4
    - squarify==0.4.3


